"""Updated SQLAlchemy queries

Revision ID: 0b9b84718838
Revises: 1a33ef5cd429
Create Date: 2024-07-04 17:39:55.003125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9b84718838'
down_revision = '1a33ef5cd429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
