"""your message

Revision ID: 1a33ef5cd429
Revises: bea464687aa7
Create Date: 2024-07-04 17:34:25.147262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a33ef5cd429'
down_revision = 'bea464687aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
